/**
 * SyntaxKind — token kinds and reserved future node kinds.
 * Prompt 3 §13, §22.
 */
export const enum SyntaxKind {
  Unknown = 0,
  EndOfFile = 1,
  Invalid = 2,
  // Literals
  Identifier = 100,
  IntegerLiteral = 101,
  FloatLiteral = 102,
  StringLiteral = 103,
  RawStringLiteral = 104,
  MultilineStringLiteral = 105,
  BooleanLiteral = 106,
  AbsenceLiteral = 107,
  VersionLiteral = 108,
  PathLiteral = 109,
  // Keywords
  KeywordSeed = 200,
  KeywordTitle = 201,
  KeywordVersion = 202,
  KeywordDomain = 203,
  KeywordId = 204,
  KeywordRequires = 205,
  KeywordOptional = 206,
  KeywordIntent = 207,
  KeywordPurpose = 208,
  KeywordGoal = 209,
  KeywordNonGoal = 210,
  KeywordImport = 211,
  KeywordLocal = 212,
  KeywordAs = 213,
  KeywordExport = 214,
  KeywordPrivate = 215,
  KeywordGene = 216,
  KeywordConfidence = 217,
  KeywordInvariant = 218,
  KeywordConstraints = 219,
  KeywordRequire = 220,
  KeywordForbid = 221,
  KeywordEntropy = 222,
  KeywordAlgorithm = 223,
  KeywordRoot = 224,
  KeywordChannel = 225,
  KeywordStream = 226,
  KeywordEffects = 227,
  KeywordFilesystem = 228,
  KeywordNetwork = 229,
  KeywordProcess = 230,
  KeywordEnvironment = 231,
  KeywordClock = 232,
  KeywordModelInference = 233,
  KeywordBudget = 234,
  KeywordTarget = 235,
  KeywordEquivalence = 236,
  KeywordExtension = 237,
  KeywordSchema = 238,
  KeywordCapability = 239,
  KeywordLineage = 240,
  KeywordProvenance = 241,
  KeywordValidation = 242,
  KeywordCompatibility = 243,
  KeywordNode = 244,
  KeywordEdge = 245,
  KeywordTrue = 246,
  KeywordFalse = 247,
  KeywordNone = 248,
  KeywordDeny = 249,
  KeywordAllow = 250,
  KeywordReadOnly = 251,
  // Punctuation
  LeftBrace = 300,
  RightBrace = 301,
  LeftBracket = 302,
  RightBracket = 303,
  LeftParen = 304,
  RightParen = 305,
  Comma = 306,
  Colon = 307,
  DoubleColon = 308,
  Dot = 309,
  DotDot = 310,
  At = 311,
  Arrow = 312,
  Question = 313,
  Semicolon = 314,
  // Operators
  Assign = 400,
  Plus = 401,
  Minus = 402,
  Star = 403,
  Slash = 404,
  Percent = 405,
  Bang = 406,
  EqualEqual = 407,
  BangEqual = 408,
  Less = 409,
  LessEqual = 410,
  Greater = 411,
  GreaterEqual = 412,
  LogicalAnd = 413,
  LogicalOr = 414,
  Range = 415,
  In = 416,
  // Trivia kinds
  WhitespaceTrivia = 500,
  NewlineTrivia = 501,
  LineCommentTrivia = 502,
  BlockCommentTrivia = 503,
  DocumentationCommentTrivia = 504,
  ByteOrderMarkTrivia = 505,
  // Node kinds (parser)
  CompilationUnit = 600,
  ModuleDeclaration = 601,
  ImportDeclaration = 602,
  ExportDeclaration = 603,
  SeedDeclaration = 604,
  DomainDeclaration = 605,
  IntentDeclaration = 606,
  GeneDeclaration = 607,
  ConstraintBlock = 608,
  EntropyBlock = 609,
  EffectsBlock = 610,
  BudgetBlock = 611,
  TargetDeclaration = 612,
  ExtensionDeclaration = 613,
  TypeExpression = 614,
  Expression = 615,
  Block = 616,
}

export const KEYWORD_KINDS: ReadonlyMap<string, SyntaxKind> = new Map([
  ['seed', SyntaxKind.KeywordSeed],
  ['title', SyntaxKind.KeywordTitle],
  ['version', SyntaxKind.KeywordVersion],
  ['domain', SyntaxKind.KeywordDomain],
  ['id', SyntaxKind.KeywordId],
  ['requires', SyntaxKind.KeywordRequires],
  ['optional', SyntaxKind.KeywordOptional],
  ['intent', SyntaxKind.KeywordIntent],
  ['purpose', SyntaxKind.KeywordPurpose],
  ['goal', SyntaxKind.KeywordGoal],
  ['non_goal', SyntaxKind.KeywordNonGoal],
  ['import', SyntaxKind.KeywordImport],
  ['local', SyntaxKind.KeywordLocal],
  ['as', SyntaxKind.KeywordAs],
  ['export', SyntaxKind.KeywordExport],
  ['private', SyntaxKind.KeywordPrivate],
  ['gene', SyntaxKind.KeywordGene],
  ['confidence', SyntaxKind.KeywordConfidence],
  ['invariant', SyntaxKind.KeywordInvariant],
  ['constraints', SyntaxKind.KeywordConstraints],
  ['require', SyntaxKind.KeywordRequire],
  ['forbid', SyntaxKind.KeywordForbid],
  ['entropy', SyntaxKind.KeywordEntropy],
  ['algorithm', SyntaxKind.KeywordAlgorithm],
  ['root', SyntaxKind.KeywordRoot],
  ['channel', SyntaxKind.KeywordChannel],
  ['stream', SyntaxKind.KeywordStream],
  ['effects', SyntaxKind.KeywordEffects],
  ['filesystem', SyntaxKind.KeywordFilesystem],
  ['network', SyntaxKind.KeywordNetwork],
  ['process', SyntaxKind.KeywordProcess],
  ['environment', SyntaxKind.KeywordEnvironment],
  ['clock', SyntaxKind.KeywordClock],
  ['model_inference', SyntaxKind.KeywordModelInference],
  ['budget', SyntaxKind.KeywordBudget],
  ['target', SyntaxKind.KeywordTarget],
  ['equivalence', SyntaxKind.KeywordEquivalence],
  ['extension', SyntaxKind.KeywordExtension],
  ['schema', SyntaxKind.KeywordSchema],
  ['capability', SyntaxKind.KeywordCapability],
  ['lineage', SyntaxKind.KeywordLineage],
  ['provenance', SyntaxKind.KeywordProvenance],
  ['validation', SyntaxKind.KeywordValidation],
  ['compatibility', SyntaxKind.KeywordCompatibility],
  ['node', SyntaxKind.KeywordNode],
  ['edge', SyntaxKind.KeywordEdge],
  ['true', SyntaxKind.KeywordTrue],
  ['false', SyntaxKind.KeywordFalse],
  ['none', SyntaxKind.KeywordNone],
  ['deny', SyntaxKind.KeywordDeny],
  ['allow', SyntaxKind.KeywordAllow],
  ['read_only', SyntaxKind.KeywordReadOnly],
]);

export const PUNCTUATION_KINDS: ReadonlyMap<string, SyntaxKind> = new Map([
  ['{', SyntaxKind.LeftBrace],
  ['}', SyntaxKind.RightBrace],
  ['[', SyntaxKind.LeftBracket],
  [']', SyntaxKind.RightBracket],
  ['(', SyntaxKind.LeftParen],
  [')', SyntaxKind.RightParen],
  [',', SyntaxKind.Comma],
  [':', SyntaxKind.Colon],
  ['::', SyntaxKind.DoubleColon],
  ['.', SyntaxKind.Dot],
  ['..', SyntaxKind.DotDot],
  ['@', SyntaxKind.At],
  ['->', SyntaxKind.Arrow],
  ['?', SyntaxKind.Question],
  [';', SyntaxKind.Semicolon],
]);

export const OPERATOR_KINDS: ReadonlyMap<string, SyntaxKind> = new Map([
  ['=', SyntaxKind.Assign],
  ['+', SyntaxKind.Plus],
  ['-', SyntaxKind.Minus],
  ['*', SyntaxKind.Star],
  ['/', SyntaxKind.Slash],
  ['%', SyntaxKind.Percent],
  ['!', SyntaxKind.Bang],
  ['==', SyntaxKind.EqualEqual],
  ['!=', SyntaxKind.BangEqual],
  ['<', SyntaxKind.Less],
  ['<=', SyntaxKind.LessEqual],
  ['>', SyntaxKind.Greater],
  ['>=', SyntaxKind.GreaterEqual],
  ['&&', SyntaxKind.LogicalAnd],
  ['||', SyntaxKind.LogicalOr],
  ['..', SyntaxKind.Range],
  ['in', SyntaxKind.In],
]);

export function isKeyword(kind: SyntaxKind): boolean {
  return kind >= SyntaxKind.KeywordSeed && kind <= SyntaxKind.KeywordReadOnly;
}

export function isTrivia(kind: SyntaxKind): boolean {
  return kind >= SyntaxKind.WhitespaceTrivia && kind <= SyntaxKind.ByteOrderMarkTrivia;
}
