/** Frontend diagnostic registry - unified catalog. Prompt 3 §18. */
export interface DiagnosticEntry { readonly code: string; readonly severity: string; readonly category: string; readonly phase: string; readonly description: string; readonly emitterFile: string; readonly testedInFile: string; }
export var FRONTEND_DIAGNOSTIC_REGISTRY = [
  { code: "GSPL-MODULE-NOT-FOUND", severity: "error", category: "module", phase: "module", description: "Module or import path could not be resolved", emitterFile: "packages/frontend/src/module-resolver.ts", testedInFile: "packages/frontend/test/module-resolver.test.ts" },
  { code: "GSPL-MODULE-INVALID-EXTENSION", severity: "error", category: "module", phase: "module", description: "Imported file has an unsupported extension", emitterFile: "packages/frontend/src/module-resolver.ts", testedInFile: "packages/frontend/test/module-resolver.test.ts" },
  { code: "GSPL-MODULE-TOO-MANY", severity: "error", category: "module", phase: "module", description: "Too many modules in the resolution graph", emitterFile: "packages/frontend/src/module-resolver.ts", testedInFile: "packages/frontend/test/module-resolver.test.ts" },
  { code: "GSPL-MODULE-CYCLE", severity: "error", category: "module", phase: "module", description: "Circular dependency detected among modules", emitterFile: "packages/frontend/src/module-resolver.ts", testedInFile: "packages/frontend/test/module-resolver.test.ts" },
  { code: "GSPL-BIND-DUPLICATE-DECLARATION", severity: "error", category: "binding", phase: "binding", description: "Duplicate declaration in same scope", emitterFile: "packages/frontend/src/binding.ts", testedInFile: "packages/frontend/test/binding.test.ts" },
  { code: "GSPL-BIND-UNRESOLVED-NAME", severity: "error", category: "binding", phase: "binding", description: "Identifier reference could not be resolved", emitterFile: "packages/frontend/src/binding.ts", testedInFile: "packages/frontend/test/binding.test.ts" },
  { code: "GSPL-BIND-AMBIGUOUS-NAME", severity: "error", category: "binding", phase: "binding", description: "Identifier matched multiple declarations", emitterFile: "packages/frontend/src/binding.ts", testedInFile: "packages/frontend/test/binding.test.ts" },
  { code: "GSPL-TYPE-UNKNOWN-TYPE", severity: "error", category: "type", phase: "type", description: "Named type does not match any known type", emitterFile: "packages/frontend/src/type-analysis.ts", testedInFile: "packages/frontend/test/type-analysis.test.ts" },
  { code: "GSPL-TYPE-MISMATCH", severity: "error", category: "type", phase: "type", description: "Declared type does not match inferred type", emitterFile: "packages/frontend/src/type-analysis.ts", testedInFile: "packages/frontend/test/type-analysis.test.ts" },
  { code: "GSPL-LOWER-INVALID-TYPE", severity: "error", category: "lower", phase: "lower", description: "Type could not be lowered from CST to AST", emitterFile: "packages/frontend/src/ast-lowering.ts", testedInFile: "packages/frontend/test/ast-lowering.test.ts" },
  { code: "GSPL-LOWER-INVALID-EXPR", severity: "error", category: "lower", phase: "lower", description: "Expression could not be lowered from CST to AST", emitterFile: "packages/frontend/src/ast-lowering.ts", testedInFile: "packages/frontend/test/ast-lowering.test.ts" },
  { code: "GSPL-LOWER-NO-SEED", severity: "error", category: "lower", phase: "lower", description: "No seed declaration found", emitterFile: "packages/frontend/src/canonical-lowering.ts", testedInFile: "packages/frontend/test/ir-lowering.test.ts" },
];
