var fs = require('fs');

// ── FIX 1: ir-reconstructor — add identity reconstruction, readonly fields, add packageLock ──
var recon = [
'/** IR to Seed Reconstruction — independent, no original seed — Prompt 2 §1-3 */',
'import type { CanonicalSeed } from "@gspl/seed-format";',
'import { makePrimordialSeed, canonicalizeSeed } from "@gspl/seed-format";',
'import type { GsplIrGraph, GsplIrNode, Diagnostic } from "@gspl/ir-model";',
'import type { GeneTypeRegistry } from "@gspl/gene-protocol";',
'',
'export interface ReconstructionContext {',
'  readonly geneRegistry: GeneTypeRegistry;',
'  readonly compilerVersion: string;',
'  readonly canonVersion: string;',
'  readonly limits: { readonly maxGenes: number; readonly maxConstraints: number; readonly maxDependencies: number; };',
'}',
'',
'export interface IrReconstructionResult {',
'  readonly ok: boolean;',
'  readonly seed: CanonicalSeed;',
'  readonly errors: readonly string[];',
'  readonly warnings: readonly string[];',
'}',
'',
'function findMetaNode(nodes: Map<string, GsplIrNode>, section: string): GsplIrNode | undefined {',
'  var vals = Array.from(nodes.values());',
'  for (var i = 0; i < vals.length; i++) {',
'    var n = vals[i];',
'    if (n.attributes && n.attributes.section === section) return n;',
'  }',
'  return undefined;',
'}',
'',
'function extractGeneName(nodeId: string, attrs?: Record<string,unknown>): string {',
'  var p = nodeId.split(":");',
'  return p.length >= 3 && p[0] === "n" ? p[2] : (attrs && attrs.geneName as string) || "unknown";',
'}',
'',
'export function reconstructSeedFromIr(graph: GsplIrGraph, ctx: ReconstructionContext): IrReconstructionResult {',
'  var errors: string[] = [];',
'  var reg = ctx.geneRegistry;',
'',
'  // ── Schema identity ──',
'  var schemaNode = findMetaNode(graph.nodes, "schema");',
'  var seedSchema = (schemaNode && schemaNode.value && (schemaNode.value as any).schema) || "gspl.canonical-seed";',
'  var seedSchemaVersion = (schemaNode && schemaNode.value && (schemaNode.value as any).schemaVersion) || "1.0";',
'',
'  // ── Identity fields (authoredId, revisionId, lineageId, packageId) ──',
'  var identityNode = findMetaNode(graph.nodes, "identity");',
'  var identityOverrides: any = {};',
'  if (identityNode && identityNode.value) {',
'    var idv = identityNode.value as Record<string,unknown>;',
'    if (idv.authoredId !== undefined) identityOverrides.authoredId = idv.authoredId;',
'    if (idv.revisionId !== undefined) identityOverrides.revisionId = idv.revisionId;',
'    if (idv.lineageId !== undefined) identityOverrides.lineageId = idv.lineageId;',
'    if (idv.packageId !== undefined) identityOverrides.packageId = idv.packageId;',
'  }',
'',
'  // ── Namespace, domain profile, intent ──',
'  var nsNode = findMetaNode(graph.nodes, "namespace");',
'  var namespace = (nsNode && nsNode.value) || undefined;',
'  var dpNode = findMetaNode(graph.nodes, "domainProfile");',
'  var domainProfile = (dpNode && dpNode.value) || { domainId: "seed", requiredCapabilities: [], optionalCapabilities: [] };',
'  var intentNode = findMetaNode(graph.nodes, "intent");',
'  var intent = (intentNode && intentNode.value) || { purpose: "Reconstructed from IR" };',
'',
'  // ── Genes: group fragments, lift via descriptors ──',
'  var geneGroups = new Map<string, { fragments: any[]; type: string; confidence?: number }>();',
'  graph.nodes.forEach(function(node) {',
'    var gn = extractGeneName(node.id, node.attributes);',
'    if (gn === "unknown" || gn === "seed-root" || (node.attributes && node.attributes.section)) return;',
'    var frag = { id: node.id, kind: node.kind, type: node.type, value: node.value, attributes: node.attributes, provenance: { source: node.provenance.source, originId: node.provenance.originId } };',
'    var existing = geneGroups.get(gn);',
'    if (existing) { existing.fragments.push(frag); }',
'    else { geneGroups.set(gn, { fragments: [frag], type: node.type, confidence: (node.attributes && node.attributes.confidence as number) || undefined }); }',
'  });',
'',
'  var genes: Record<string,{type:string;value:unknown;confidence?:number}> = {};',
'  geneGroups.forEach(function(group, geneName) {',
'    var geneNode = group.fragments.find(function(f: any) { return f.kind === "gene" || (f.type && reg.has(f.type)); });',
'    var typeId = (geneNode && geneNode.type) || group.type || "unknown";',
'    var desc = reg.get(typeId);',
'    if (ctx.limits.maxGenes && Object.keys(genes).length >= ctx.limits.maxGenes) { errors.push("GSPL-LIMIT-MAX-GENES"); return; }',
'    if (desc && desc.liftFromIr) {',
'      try {',
'        // Two-pass cross-reference resolution',
'        var lifted = desc.liftFromIr(group.fragments, {',
'          seedId: "reconstructed", geneName: geneName,',
'          resolveGeneValue: function(resolveTypeId: string) {',
'            var resolvedGroup = geneGroups.get(resolveTypeId);',
'            if (resolvedGroup) {',
'              var rDesc = reg.get(resolvedGroup.type);',
'              if (rDesc && rDesc.liftFromIr) {',
'                return rDesc.liftFromIr(resolvedGroup.fragments, { seedId: "reconstructed", geneName: resolveTypeId, resolveGeneValue: function() { return null; } });',
'              }',
'            }',
'            return null;',
'          }',
'        });',
'        genes[geneName] = { type: typeId, value: lifted, confidence: group.confidence };',
'      } catch(e) {',
'        errors.push("Lift error " + geneName + ": " + String(e));',
'        genes[geneName] = { type: typeId, value: (geneNode && geneNode.value) || null };',
'      }',
'    } else {',
'      genes[geneName] = { type: typeId, value: (geneNode && geneNode.value) || null, confidence: group.confidence };',
'    }',
'  });',
'',
'  function readMeta(s: string) { var n = findMetaNode(graph.nodes, s); return (n && n.value) || undefined; }',
'  var constraints = readMeta("constraints") || { valueRanges: [], structuralConditions: [], targetRestrictions: [], performanceBudgets: [], compatibilityConditions: [] };',
'  var dependencies = readMeta("dependencies") || { contextRefs: [], knowledgeRefs: [], ruleSetRefs: [], targetContracts: [] };',
'  var entropy = readMeta("entropy") || { algorithm: "gspl-splitmix64", algorithmVersion: "1.0", rootSeed: "", channels: [] };',
'  var lineage = readMeta("lineage") || { operation: "primordial", parents: [], generation: 0 };',
'  var provenance = readMeta("provenance") || { canonVersion: ctx.canonVersion };',
'  var resourceBudget = readMeta("resourceBudget") || {};',
'  var effectPermissions = readMeta("effectPermissions") || { filesystem: "none", processExecution: false, networkAccess: false, environmentAccess: false, timeAccess: false, foreignCodeExecution: false, nativeExtensions: false, modelInference: false };',
'  var validationReqs = readMeta("validationRequirements");',
'  var compatReqs = readMeta("compatibilityRequirements");',
'',
'  // ── Build seed with identity overrides ──',
'  var seed = makePrimordialSeed({',
'    schema: seedSchema as any, schemaVersion: seedSchemaVersion,',
'    namespace: namespace, domainProfile: domainProfile, intent: intent,',
'    payload: { schemaVersion: "1.0", genes: genes },',
'    constraints: constraints, dependencies: dependencies,',
'    entropy: entropy, lineage: lineage, provenance: provenance,',
'    resourceBudget: resourceBudget, effectPermissions: effectPermissions,',
'    validationRequirements: validationReqs, compatibilityRequirements: compatReqs,',
'  });',
'',
'  // Apply identity overrides AFTER makePrimordialSeed',
'  if (identityOverrides.authoredId !== undefined) (seed as any).identity.authoredId = identityOverrides.authoredId;',
'  if (identityOverrides.revisionId !== undefined) (seed as any).identity.revisionId = identityOverrides.revisionId;',
'  if (identityOverrides.lineageId !== undefined) (seed as any).identity.lineageId = identityOverrides.lineageId;',
'  if (identityOverrides.packageId !== undefined) (seed as any).identity.packageId = identityOverrides.pa
