var fs = require('fs');
var path = 'docs/audit/architecture-decisions.json';
var ad = JSON.parse(fs.readFileSync(path, 'utf-8'));

var newAdrs = [
  {id:'GSPL-ARCH-0027',subsystem:'canonical-representation',disposition:'ADOPT',rationale:'Selected Model D (Layered Hybrid): 5-layer stack adopted. Scored highest across 18 criteria. Maps to packages: seed-format (L1), ir-model (L2), compiler-core (L3-L4).',references:['GSPL-INV-0001','GSPL-INV-0013'],evidence:[{repo:'canon-foundation',file:'docs/canon/GSPL_SEED_MODEL_CANDIDATES.md'},{repo:'compiler-core',file:'test/model-evaluation.test.ts'}],confidence:'HIGH'},
  {id:'GSPL-ARCH-0028',subsystem:'seed-model',disposition:'ADOPT',rationale:'CanonicalSeed schema v1.0 with full Prompt 2 fields: identity, namespace, domain, intent, payload, constraints, dependencies, entropy, lineage, provenance, budget, permissions. Hash/non-hash separation per 4.2.',references:['GSPL-INV-0001','GSPL-INV-0005'],evidence:[{repo:'seed-format',file:'src/seed.ts'}],confidence:'HIGH'},
  {id:'GSPL-ARCH-0029',subsystem:'gene-protocol',disposition:'ADOPT',rationale:'Extensible versioned gene registry adopted. 17 types classified: 12 CORE, 4 LIBRARY, 1 SECURITY. Immutable registry with validation.',references:['GSPL-INV-0002','GSPL-INV-0007'],evidence:[{repo:'gene-protocol',file:'src/types.ts'},{repo:'gene-protocol',file:'src/dispositions.ts'}],confidence:'HIGH'},
  {id:'GSPL-ARCH-0030',subsystem:'ir-graph-model',disposition:'ADOPT',rationale:'Typed attributed IR graph: directed, multi-edge, region-based, content-addressed. 15 node kinds, 11 edge kinds. Deterministic normalization with SHA-256 hashing.',references:['GSPL-INV-0010','GSPL-INV-0013'],evidence:[{repo:'ir-model',file:'src/graph.ts'},{repo:'ir-model',file:'src/graph-ops.ts'}],confidence:'HIGH'},
  {id:'GSPL-ARCH-0031',subsystem:'graph-normalization',disposition:'ADOPT',rationale:'Canonical graph normalization: nodes by ID, edges by (from,to,kind), regions by ID. Idempotent. SHA-256 over deterministic serialization.',references:['GSPL-INV-0010'],evidence:[{repo:'ir-model',file:'src/graph-ops.ts'}],confidence:'HIGH'},
  {id:'GSPL-ARCH-0032',subsystem:'entropy',disposition:'ADOPT',rationale:'Hierarchical entropy channels: SplitMix64 with labeled forks. 6 standard channels. Order-independent for cross-process reproducibility. Golden vectors locked.',references:['GSPL-INV-0003'],evidence:[{repo:'canon-foundation',file:'src/rng/entropy-channels.ts'}],confidence:'HIGH'},
  {id:'GSPL-ARCH-0033',subsystem:'packages',disposition:'ADOPT',rationale:'Context/Knowledge/Rule package contracts adopted. Each: stable identity, version, content hash, protocol compatibility, dependencies, licenses, provenance.',references:['GSPL-INV-0015'],evidence:[{repo:'seed-format',file:'src/packages.ts'}],confidence:'MEDIUM'},
  {id:'GSPL-ARCH-0034',subsystem:'constraint-model',disposition:'ADOPT',rationale:'Constraint/Capability/Effect separation adopted. Constraints: value ranges, structural, targets, performance. Capabilities: declared operations. Effects: explicit grants, default ALL DENIED.',references:['GSPL-INV-0014'],evidence:[{repo:'ir-model',file:'src/constraints.ts'}],confidence:'HIGH'},
  {id:'GSPL-ARCH-0035',subsystem:'artifact-graph',disposition:'ADOPT',rationale:'Target-neutral artifact graph: 12 kinds (source, module, asset, scene, config, test, doc, metadata, binary, interactive, fixture, media). 8 relationship types.',references:['GSPL-INV-0013'],evidence:[{repo:'compiler-core',file:'src/artifact-graph.ts'}],confidence:'MEDIUM'},
  {id:'GSPL-ARCH-0036',subsystem:'serialization',disposition:'ADOPT',rationale:'Canonical serialization: Unicode NFKC, negative zero normalization, base64url binary encoding, UTC timestamp normalization, deterministic number serialization. JCS (RFC 8785) base.',references:['GSPL-INV-0005'],evidence:[{repo:'canon-foundation',file:'src/canonicalize/serialization.ts'}],confidence:'HIGH'},
  {id:'GSPL-ARCH-0037',subsystem:'versioning',disposition:'ADOPT',rationale:'Schema versioning and migration: 5 migration kinds, multi-step paths, migration provenance, compatibility checking, deprecation policy.',references:['GSPL-INV-0001','GSPL-INV-0016'],evidence:[{repo:'canon-foundation',file:'src/migration/versioning.ts'}],confidence:'MEDIUM'},
  {id:'GSPL-ARCH-0038',subsystem:'package-boundaries',disposition:'ADOPT',rationale:'5-package architecture: canon-foundation -> gene-protocol -> seed-format -> ir-model -> compiler-core. Strict dependency direction. No circular deps, no global singletons.',references:['GSPL-INV-0013','GSPL-INV-0015'],evidence:[{repo:'canon-foundation',file:'package.json'},{repo:'compiler-core',file:'package.json'}],confidence:'HIGH'}
];

for (var i = 0; i < newAdrs.length; i++) ad.decisions.push(newAdrs[i]);
ad.decisions.sort(function(a,b) { return a.id.localeCompare(b.id); });
fs.writeFileSync(path, JSON.stringify(ad, null, 2) + '\n');
console.log('ADRs: ' + newAdrs.length + ' new, ' + ad.decisions.length + ' total');
